apiVersion: apps/v1
kind: Deployment
metadata:
  name: mjgif
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mjgif
  template:
    metadata:
      labels:
        app: mjgif
    spec:
      containers:
      - image: okteto.dev/mjgif:latest
        name: mjgif
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "1f9e63a2-b84a-41b3-afb8-9c9674daaec0"
        - name: Vless_Path
          value: "/vl578"
        - name: Vmess_UUID
          value: "1f9e63a2-b84a-41b3-afb8-9c9674daaec0"
        - name: Vmess_Path
          value: "/vm908"
        - name: Share_Path
          value: "/v2link"
